### ISSUE TITLE
Fixed patch selection?

### ISSUE THREAD

**Issue by nexuslrf** [IGLICT/DeepFaceEditing-Jittor#7]
Just notice that this released demo uses fixed bounding boxes for eyes, nose, mouth (https://github.com/IGLICT/DeepFaceEditing-Jittor/blob/master/combine_model.py#L15). 

I wonder how do you define such bounding boxes in more general cases? Do you use the same fixed values as the ones shown in this released demo, or use some keypoint detection to generate such boxes?

**Comment by ty625911724** [comment]
We use the fixed boxes for each components and the faces should be aligned first. The alignment is the same as FFHQ dataset. Thanks!
